# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Code Crafted Ventures
email: djefobey@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  At CodeCrafted Ventures, we are the architects of a digital evolution, 
  pioneering the intersection of innovation and technology. 
  With a passion for precision and an unwavering commitment to excellence, 
  we embark on a journey where code is not just lines but a canvas for creativity. 
  Our mission is clear: to transform ambitious ideas into seamless, 
  cutting-edge digital experiences. We believe in the power of innovation to shape the future, 
  and at CodeCrafted Ventures, we craft more than just code; we craft possibilities. 
  Join us in redefining the landscape of technology, where every project is a testament to our 
  dedication to brilliance, and every line of code tells a story of innovation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://CodeCraftedVentures.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CodeCraftedVentures
github_username:  CodeCraftedVentures

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
